name: Pull Request
description: "Fill out this form when creating a PR."

title: "[PR]: "  # Pre-fills PR title
labels: ["pending review"]  # Auto-adds a label

body:
  - type: input
    id: pr_title
    attributes:
      label: "🔖 PR Title"
      description: "Provide a short and clear PR title."
      placeholder: "Enter PR title here"

  - type: textarea
    id: summary
    attributes:
      label: "📌 Summary"
      description: "Provide a concise summary of the changes made in this PR."
      placeholder: "Enter summary here"

  - type: checkboxes
    id: changes
    attributes:
      label: "🔄 Changes Introduced"
      description: "Select the changes introduced in this PR."
      options:
        - label: "Feature"
        - label: "Bug fix"
        - label: "Refactoring"
        - label: "Documentation updates"

  - type: textarea
    id: testing
    attributes:
      label: "🛠️ How Has This Been Tested?"
      description: "Describe the testing strategy used for this PR."
      placeholder: "Enter testing details here"

  - type: checkboxes
    id: impact
    attributes:
      label: "⚠️ Impact Analysis"
      description: "Mention any breaking changes."
      options:
        - label: "Affects API"
        - label: "Affects Database"
        - label: "Affects UI"
        - label: "Requires Migration"
        - label: "No Breaking Changes"

  - type: textarea
    id: additional_notes
    attributes:
      label: "📝 Additional Notes"
      description: "Add any other relevant information."
      placeholder: "Enter additional notes here"
